In [164]:
import pandas as pd

In [165]:
node_num = 9 
batch_size = 32
epochs = 1000

In [166]:
pd.set_option('display.max_columns', None)

In [167]:
df = pd.read_csv('./extend.csv')

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                1309 non-null   int64  
 1   PassengerId               1309 non-null   int64  
 2   Pclass                    1309 non-null   int64  
 3   Name                      1309 non-null   object 
 4   Sex                       1309 non-null   object 
 5   SibSp                     1309 non-null   int64  
 6   Parch                     1309 non-null   int64  
 7   Ticket                    1309 non-null   object 
 8   Fare                      1309 non-null   float64
 9   Cabin                     1309 non-null   object 
 10  Embarked                  1307 non-null   object 
 11  WikiId                    1304 non-null   float64
 12  Name_wiki                 1304 non-null   object 
 13  Age                       1309 non-null   float64
 14  Hometown

In [169]:
df.describe()

Unnamed: 0  PassengerId       Pclass        SibSp        Parch  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    654.000000   655.000000     2.294882     0.498854     0.385027   
std     378.020061   378.020061     0.837836     1.041658     0.865560   
min       0.000000     1.000000     1.000000     0.000000     0.000000   
25%     327.000000   328.000000     2.000000     0.000000     0.000000   
50%     654.000000   655.000000     3.000000     0.000000     0.000000   
75%     981.000000   982.000000     3.000000     1.000000     0.000000   
max    1308.000000  1309.000000     3.000000     8.000000     9.000000   

              Fare       WikiId          Age        Class       Family  \
count  1309.000000  1304.000000  1309.000000  1309.000000  1309.000000   
mean     33.275582   658.534509    29.415829     2.291062     0.883881   
std      51.743887   380.377373    13.722088     0.841446     1.583639   
min       0.000000     1.000000     0.170000     1.000000     0.000000   
25%       7.895800   326.750000    21.000000     1.000000     0.000000   
50%      14.454200   661.500000    28.000000     3.000000     0.000000   
75%      31.275000   987.250000    37.000000     3.000000     1.000000   
max     512.329200  1314.000000    74.000000     3.000000    10.000000   

          Survived  Cabin_Numbers    Real_Fare  Cabin Position  
count  1309.000000   2.890000e+02  1200.000000     1252.000000  
mean      0.381971   1.008873e+06    12.780953        2.399361  
std       0.486055   7.521717e+06    10.592790        0.749271  
min       0.000000   2.000000e+00     0.000000        1.000000  
25%       0.000000   2.600000e+01     7.274975        2.000000  
50%       0.000000   4.600000e+01     8.050000        3.000000  
75%       1.000000   9.200000e+01    13.000000        3.000000  
max       1.000000   5.759637e+07    82.506933        3.000000

In [170]:
df

Unnamed: 0  PassengerId  Pclass  \
0              0            1       3   
1              1            2       1   
2              2            3       3   
3              3            4       1   
4              4            5       3   
...          ...          ...     ...   
1304        1304         1305       3   
1305        1305         1306       1   
1306        1306         1307       3   
1307        1307         1308       3   
1308        1308         1309       3   

                                                   Name     Sex  SibSp  Parch  \
0                               Braund, Mr. Owen Harris    male      1      0   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                                Heikkinen, Miss. Laina  female      0      0   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                              Allen, Mr. William Henry    male      0      0   
...                                                 ...     ...    ...    ...   
1304                                 Spector, Mr. Woolf    male      0      0   
1305                       Oliva y Ocana, Dona. Fermina  female      0      0   
1306                       Saether, Mr. Simon Sivertsen    male      0      0   
1307                                Ware, Mr. Frederick    male      0      0   
1308                           Peter, Master. Michael J    male      1      1   

                  Ticket      Fare    Cabin Embarked  WikiId  \
0              A/5 21171    7.2500  Unknown        S   691.0   
1               PC 17599   71.2833      C85        C    90.0   
2       STON/O2. 3101282    7.9250  Unknown        S   865.0   
3                 113803   53.1000     C123        S   127.0   
4                 373450    8.0500  Unknown        S   627.0   
...                  ...       ...      ...      ...     ...   
1304           A.5. 3236    8.0500  Unknown        S  1227.0   
1305            PC 17758  108.9000     C105        C   229.0   
1306  SOTON/O.Q. 3101262    7.2500  Unknown        S  1169.0   
1307              359309    8.0500  Unknown        S  1289.0   
1308                2668   22.3583  Unknown        C   702.0   

                                       Name_wiki   Age  \
0                        Braund, Mr. Owen Harris  22.0   
1     Cumings, Mrs. Florence Briggs (née Thayer)  35.0   
2                          Heikkinen, Miss Laina  26.0   
3             Futrelle, Mrs. Lily May (née Peel)  35.0   
4                       Allen, Mr. William Henry  35.0   
...                                          ...   ...   
1304                          Spector, Mr. Woolf  23.0   
1305        and maid, Doña Fermina Oliva y Ocana  39.0   
1306                 Sæther, Mr. Simon Sivertsen  43.0   
1307                 Ware, Mr. Frederick William  34.0   
1308             Butrus-Youssef, Master Makhkhul   4.0   

                                Hometown Embarked_wiki  \
0             Bridgerule, Devon, England             S   
1                 New York, New York, US             C   
2                     Jyväskylä, Finland             S   
3            Scituate, Massachusetts, US             S   
4     Birmingham, West Midlands, England             S   
...                                  ...           ...   
1304                     London, England             S   
1305                       Madrid, Spain             C   
1306        Skaun, Sør-Trøndelag, Norway             S   
1307          Greenwich, London, England             S   
1308                   Sar'al[81], Syria             C   

                                  Destination Lifeboat  Body  Class  Family  \
0     Qu'Appelle Valley, Saskatchewan, Canada      NaN   NaN    3.0       1   
1                      New York, New York, US        4   NaN    1.0       1   
2                               New York City      14?   NaN    3.0       0   
3                 Scituate, Massachusetts, US        D   NaN 

In [171]:
feature = ['Class', 'Sex', 'Real_Fare', 'Family', 'Title', 'Predict_Cabin', 'General Region', 'Embarked', 'Cabin Position']
X = df[feature].copy()
Y = df['Survived']
print(X, Y)

      Class     Sex  Real_Fare  Family   Title Predict_Cabin General Region  \
0       3.0    male    7.25000       1      Mr             D        British   
1       1.0  female   35.64165       1     Mrs             C  North America   
2       3.0  female    7.92500       0    Miss             E    West Europe   
3       1.0  female   26.55000       1     Mrs             C  North America   
4       3.0    male    8.05000       0      Mr             F        British   
...     ...     ...        ...     ...     ...           ...            ...   
1304    3.0    male    8.05000       0      Mr             F        British   
1305    1.0  female        NaN       0    Lady             C    West Europe   
1306    3.0    male    7.25000       0      Mr             E   North Europe   
1307    3.0    male    8.05000       0      Mr             F        British   
1308    3.0    male        NaN       2  Master       Unknown      Near East   

     Embarked  Cabin Position  
0           S      

In [172]:
X.isna().sum()

Class               0
Sex                 0
Real_Fare         109
Family              0
Title               0
Predict_Cabin       0
General Region      0
Embarked            2
Cabin Position     57
dtype: int64

In [173]:
mask = X.isna().any(axis=1)
X = X[~mask]
Y = Y[~mask] 

In [174]:
X.isna().sum()

Class             0
Sex               0
Real_Fare         0
Family            0
Title             0
Predict_Cabin     0
General Region    0
Embarked          0
Cabin Position    0
dtype: int64

In [175]:
Y.isna().sum()

0

In [176]:
import numpy as np
sex = X['Sex']
X['Sex'] = np.where(sex == 'Male', 1, 0)

In [177]:
X['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [178]:
em = X['Embarked']
X['Embarked'] = np.where(em == 'C', 0, np.where(em == 'Q', 1, 2))

In [179]:
X['Predict_Cabin'].unique()

array(['D', 'C', 'E', 'F', 'G', 'A', 'B', 'T'], dtype=object)

In [180]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()
X['Title'] = label_encoder.fit_transform(X['Title'])
X['General Region'] = label_encoder.fit_transform(X['General Region'])
X['Predict_Cabin'] = label_encoder.fit_transform(X['Predict_Cabin'])

In [181]:
print(X['Title'].unique())
print(X['General Region'].unique())
print(X['Predict_Cabin'].unique())

[ 9 10  8  7  2 12  3 11  6  5  1  0  4]
[ 1  8 12  9  7  4  6  2  3 11  0 10  5]
[3 2 4 5 6 0 1 7]


In [182]:
import numpy as np
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [183]:
from keras import Sequential
from keras.layers import Dense
from keras.initializers import RandomUniform

NN = Sequential()
NN.add(Dense(units = node_num, kernel_initializer = RandomUniform(), activation = 'sigmoid', input_dim = 9))
NN.add(Dense(units = 1, kernel_initializer = RandomUniform(), activation = 'sigmoid'))
NN.summary()

c:\Users\90586\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 9)              │            90 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100 (400.00 B)

 Trainable params: 100 (400.00 B)

 Non-trainable params: 0 (0.00 B)

In [184]:
NN.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
NN.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)

Epoch 1/1000


26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 560us/step - accuracy: 0.6791 - loss: 0.6810 
Epoch 2/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.6384 - loss: 0.6673
Epoch 3/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 0.6567 - loss: 0.6512
Epoch 4/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 0.6481 - loss: 0.6495
Epoch 5/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.6799 - loss: 0.6272
Epoch 6/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.6334 - loss: 0.6528
Epoch 7/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.6494 - loss: 0.6381
Epoch 8/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.6603 - loss: 0.6299
Epoch 9/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.6493 - loss: 0.6287
Epoch 10/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.6238 - loss: 0.6497
Epoch 11/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.6363 - loss: 0.6425
Epoch 12/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0

In [185]:
import time
from datetime import datetime

current_timestamp = time.time()
dt_object = datetime.fromtimestamp(current_timestamp)
formatted_time = dt_object.strftime('%Y%m%d%H%M%S')

In [186]:
NN.save(f'plus_{node_num}_{epochs}_{batch_size}.keras')  

In [187]:
#from keras.models import load_model
#NN= load_model(f'refine_{node_num}.keras')

In [188]:
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score, classification_report
y_pred = NN.predict(x_test)
y_pred = [1 if item > 0.5 else 0 for item in y_pred]
print(y_pred)

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,

In [ ]:
file_name = f'model_evaluation.txt'
with open(file_name, 'a') as f:
    f.write('**************************')
    f.write(f'node num: {node_num}\n')
    f.write(f'epochs: {epochs}\n')
    f.write(f'batch_size: {batch_size}\n')
    f.write(f'accs: {accuracy:.4f}\n')
    f.write(f'recall: {recall:.4f}\n')
    f.write(f'F1 score: {f1:.4f}\n')
    f.write(f'precision: {precision:.4f}\n')
    
    report = classification_report(y_test, y_pred)
    f.write("\nreport:\n")
    f.write(report)

print(f"Evaluation results saved to {file_name}")

Evaluation results saved to model_evaluation.txt
